<h2><center>Assignment 5</center></h2>
<h3><center>Programming for Data Science 2026</center></h3>
<b><center>Deadline: 14:00, April 2, 2026</center></b>

- The exercise will be marked as **passed** if you get **at least 10/16** points.

- Exercises must be handed in via **ILIAS** (Homework assignments). Submit your work as a **compressed (.zip)** file containing **one** `.py` **or** `.ipynb` file with **all exercises**.

- The name of **both** the `.zip` file and the `.py`/`.ipynb` file must be the *SurnameName* of the **two group members**, separated by an underscore.  
  Example: Tim Tabellen and Lara Lambda → `TabellenTim_LambdaLara.zip`  
  (The `.py`/`.ipynb` file must have the same name.)

- Use **comments** to explain your code and demonstrate that you understand the solutions and can discuss them.

- You are not expected to collaborate outside your group. Submitting other groups’ code as your own will result in **0 points**.

- For general questions about the lecture content, assignments, or the exam, please use the **ILIAS forum**.

- For individual questions about lecture content and the exam, contact: *roland.widmer@students.unibe.ch*  

- For individual questions about the exercises or grading, contact: *julien.brunner@students.unibe.ch* or *aline.steiner@students.unibe.ch*

#### Exercise 1: Pandas DataFrame from scratch *(2.5 points)*

1. Create a DataFrame *mountains_df* with the columns **name**, **height**, and **first_ascent**, as below:

|**name**|**height**|**first_ascent**|
|:---|:---|:---|
|Mont Blanc|46950|1786|
|Monte Rosa|4634|1855|
|Grande Ruine|3765|1873|
|Piz Sena|3075|1901|

Do not specify a specific column as an index.

In [7]:
# TODO
import pandas as pd
mountains_df = pd.DataFrame({
    'name': ['Mont Blanc', 'Monte Rosa', 'Grande Ruine', 'Piz Sena'],
    'height': [46950, 4634, 3765, 3075],
    'first_ascent': [1786, 1855, 1873, 1901]
})
mountains_df

           name  height  first_ascent
0    Mont Blanc    4695          1786
1    Monte Rosa    4634          1855
2  Grande Ruine    3765          1873
3      Piz Sena    3075          1901

2. Sort `mountains_df` by first_ascent in descending order and store it in `sorted_mountains_df`. Then explain the difference between `.iloc[0]` and `.loc[0]` on this sorted DataFrame.

In [5]:
# TODO
sorted_mountains_df = mountains_df.sort_values('first_ascent', ascending=False)
sorted_mountains_df
print(sorted_mountains_df.loc[0])
print(sorted_mountains_df.iloc[0])

name            Mont Blanc
height                4695
first_ascent          1786
Name: 0, dtype: object
name            Piz Sena
height              3075
first_ascent        1901
Name: 3, dtype: object

**Your answer**: TODO
.iloc[0] returns the value at row 0 by position while .loc[0] returns the row with index value = 0

3. Correct the height of Mont Blanc by replacing the incorrect value `46950` with the correct value `4695` in the DataFrame Use an indexing approach that clearly identifies the correct row, then briefly explain your choice.

In [8]:
# TODO
mountains_df.loc[mountains_df['name'] == 'Mont Blanc', 'height'] = 4695

**Your answer**: TODO
Using a specific boolean condition where we search up directly for the name of the mountain is better than relying on its index. This is because we would need to know what index the item is at which could lead to mistakes, where as looking up for exactly what we want is unambigous.

4. Print all rows of `mountains_df` where the first ascent was between 1800 and 1900 (inclusive).

In [4]:
# TODO
print(mountains_df[(mountains_df['first_ascent'] >= 1800) & (mountains_df['first_ascent'] <= 1900)])

5. Create a new column `height_feet` and calculate the height in feet using vectorized operations (no loops) and the following identity:

$1 \mathrm{ft} = 3.280839895 \mathrm{m}$

In [10]:
# TODO
mountains_df['height_feet'] = mountains_df['height'] * 3.280839895
mountains_df

           name  height  first_ascent   height_feet
0    Mont Blanc    4695          1786  15403.543307
1    Monte Rosa    4634          1855  15203.412073
2  Grande Ruine    3765          1873  12352.362205
3      Piz Sena    3075          1901  10088.582677

#### Exercise 2: Names I *(3 points)*

We start with two pandas Series that contain fictional counts of selected names in Bern and Zurich.

In [12]:
import pandas as pd

names_bern = pd.Series(
    [110, 160, 160],
    index=["Anna", "Ben", "Clara"]
)

names_zurich = pd.Series(
    [100, 70, 170],
    index=["Anna", "Clara", "David"]
)

1. Add them together to get the combined count of the names in Bern and Zurich and store the Series in `names_combined`. Missing names in a single Series should be treated as 0. Use appropriate pandas methods and print the result. 

Hint: The argument `fill_value` might be helpful

In [13]:
# TODO
names_combined = names_bern.add(names_zurich, fill_value=0)
print(names_combined)

Anna     210.0
Ben      160.0
Clara    230.0
David    170.0
dtype: float64

2. Print `names_combined` sorted by name (ascending).

In [15]:
# TODO
print(names_combined.sort_index())

Anna     210.0
Ben      160.0
Clara    230.0
David    170.0
dtype: float64

3. Print the most frequent name.

Hint: use a method that works like `argmax` but works on the labels.

In [16]:
# TODO
print(names_combined.idxmax())

Clara

#### Exercise 3: Names II *(4 points)*

The dataset for this exercise contains the counts of first names of the population by gender for the years 2024 and 2016.

Source: [Federal Statistical Office](https://www.bfs.admin.ch/bfs/en/home/statistics/population/births-deaths/names-switzerland.assetdetail.36062343.html)

Note: For privacy reasons, names with counts lower than 3 were counted as `0`.

1. Load the CSV file `data/csv/names.csv` as a dataframe `first_names_df`.

In [22]:
# TODO
first_names_df = pd.read_csv('../data/csv/names.csv')
first_names_df

          name  female  male  year
0         Aada      10     0  2016
1        Aadam       0     4  2016
2        Aadan       0     8  2016
3        Aadel       0     3  2016
4       Aadesh       0     5  2016
...        ...     ...   ...   ...
123018   Ünsal       0    12  2024
123019  Ünzile       7     0  2024
123020   Üsame       0     6  2024
123021  Üzeyir       0    17  2024
123022   Üçler       0     3  2024

[123023 rows x 4 columns]

2. Create a new column `total` containing the sum of the male and female counts.

In [25]:
# TODO
first_names_df['total'] = first_names_df['male'] + first_names_df['female']

3. For the year 2024, calculate the the percentage of distinct names whose total count is below 100 (i.e., percentage of rare first names).

In [26]:
# TODO
df_2024 = first_names_df[first_names_df['year'] == 2024]
percentage_rare = (df_2024['total'] < 100).sum() / len(df_2024) * 100
print(percentage_rare)

90.52921044372376

4. Which 5 names had the biggest increase in 2024 compared to 2016?

Hint: create a pandas Series per year. Exercise 2 might help you.

In [27]:
# TODO
df_2016 = first_names_df[first_names_df['year'] == 2016].set_index('name')['total']
df_2024 = first_names_df[first_names_df['year'] == 2024].set_index('name')['total']

increase = df_2024.sub(df_2016, fill_value=0)
print(increase.nlargest(5))

name
Noah     4225.0
Mia      3520.0
Sofia    3495.0
Liam     3483.0
Luca     3416.0
Name: total, dtype: float64

#### Exercise 4: Spotify *(4 points)*

1. Load `data/csv/spotify_songs.csv` as a pandas DataFrame.

In [32]:
songs = pd.read_csv("../data/csv/spotify_songs.csv")

2. Count the number of missing values in each column and drop the rows with the missing values. Store the cleaned DataFrame in `spotify_df_clean`.

In [33]:
    # TODO
missing_counts = songs.isna().sum()
spotify_df_clean = songs.dropna()
print(missing_counts)
print(len(songs), len(spotify_df_clean))

spotify_id              0
name                    0
artists                 0
daily_rank              0
daily_movement          0
weekly_movement         0
country               150
snapshot_date           0
popularity              0
is_explicit             0
duration_ms             0
album_name              0
album_release_date      0
danceability            0
energy                  0
key                     0
loudness                0
mode                    0
speechiness             0
acousticness            0
instrumentalness        0
liveness                0
valence                 0
tempo                   0
time_signature          0
dtype: int64
10000 9850

3. Find the songs with the best rank (`daily_rank`, i.e., the lowest) on the 17.02.2025 (`snapshot_date`). Print the song name and the artist and the country in which the song had lowest rank.

In [34]:
# TODO
target_date = '2025-02-17'
daily = spotify_df_clean[spotify_df_clean['snapshot_date'] == target_date]
best = daily['daily_rank'].min()
top = daily[daily['daily_rank'] == best]
print(top[['name', 'artists', 'country']])

                                     name                        artists  \
50                      luther (with sza)            Kendrick Lamar, SZA
100   Seven (feat. Latto) (Explicit Ver.)               Jung Kook, Latto
150                                 VeLDÁ  Bad Bunny, Omar Courtz, Dei V
200                          Amor de Vago          La T y La M, Malandro
250                     luther (with sza)            Kendrick Lamar, SZA
...                                   ...                            ...
3338                                 APT.               ROSÉ, Bruno Mars
3388                    luther (with sza)            Kendrick Lamar, SZA
3438                        Wackelkontakt                         Oimara
3488                         Amor de Vago          La T y La M, Malandro
3538                         Running Wild                            Jin

     country
50        ZA
100       VN
150       VE
200       UY
250       US
...      ...
3338      BE
3388      AU
3438      AT
3488      AR
3538      AE

[71 rows x 3 columns]

4. Map the country abbreviations to the full country names (e.g., ZA -> South Africa) and store the country name in a new column `country_name`.

In [35]:
country_dict = {
    'ZA': 'South Africa',
    'VN': 'Vietnam',
    'VE': 'Venezuela',
    'UY': 'Uruguay',
    'US': 'United States',
    'UA': 'Ukraine',
    'TW': 'Taiwan',
    'TR': 'Turkey',
    'TH': 'Thailand',
    'SV': 'El Salvador',
    'SK': 'Slovakia',
    'SG': 'Singapore',
    'SE': 'Sweden',
    'SA': 'Saudi Arabia',
    'RO': 'Romania',
    'PY': 'Paraguay',
    'PT': 'Portugal',
    'PL': 'Poland',
    'PK': 'Pakistan',
    'PH': 'Philippines',
    'PE': 'Peru',
    'PA': 'Panama',
    'NZ': 'New Zealand',
    'NO': 'Norway',
    'NL': 'Netherlands',
    'NI': 'Nicaragua',
    'NG': 'Nigeria',
    'MY': 'Malaysia',
    'MX': 'Mexico',
    'MA': 'Morocco',
    'LV': 'Latvia',
    'LU': 'Luxembourg',
    'LT': 'Lithuania',
    'KZ': 'Kazakhstan',
    'KR': 'South Korea',
    'JP': 'Japan',
    'IT': 'Italy',
    'IS': 'Iceland',
    'IN': 'India',
    'IL': 'Israel',
    'IE': 'Ireland',
    'ID': 'Indonesia',
    'HU': 'Hungary',
    'HN': 'Honduras',
    'HK': 'Hong Kong',
    'GT': 'Guatemala',
    'GR': 'Greece',
    'FR': 'France',
    'FI': 'Finland',
    'ES': 'Spain',
    'EG': 'Egypt',
    'EE': 'Estonia',
    'EC': 'Ecuador',
    'DO': 'Dominican Republic',
    'DK': 'Denmark',
    'DE': 'Germany',
    'CZ': 'Czech Republic',
    'CR': 'Costa Rica',
    'CO': 'Colombia',
    'CL': 'Chile',
    'CH': 'Switzerland',
    'CA': 'Canada',
    'BY': 'Belarus',
    'BR': 'Brazil',
    'BO': 'Bolivia',
    'BG': 'Bulgaria',
    'BE': 'Belgium',
    'AU': 'Australia',
    'AT': 'Austria',
    'AR': 'Argentina',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom'
}

# TODO
spotify_df_clean['country_name'] = spotify_df_clean['country'].map(country_dict)
spotify_df_clean[['country', 'country_name']].head()

   country  country_name
50      ZA  South Africa
51      ZA  South Africa
52      ZA  South Africa
53      ZA  South Africa
54      ZA  South Africa

#### Exercise 5: Distances *(4 points)*

In this exercise, we want to calculate the distances from Bern to other cities in the world.

Source: [https://simplemaps.com/data/world-cities](https://simplemaps.com/data/world-cities)

1. Load the `data/csv/worldcities.csv` using pandas and store it in the variable `cities_df`.

In [28]:
# TODO
cities_df = pd.read_csv('../data/csv/worldcities.csv')

2. For the next task, we need the latitude and longitude in radians instead of degrees. Create new columns `lat_rad` and `lng_rad` with the converted value in radians.

Hint: Use the suitable NumPy Ufunc.

In [29]:
# TODO

import numpy as np
cities_df['lat_rad'] = np.radians(cities_df['lat'])
cities_df['lng_rad'] = np.radians(cities_df['lng'])

cities_df.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,lat_rad,lng_rad
0,Tokyo,Tokyo,35.6870,139.7495,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764,0.622856,2.439089
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077,-0.107774,1.864492
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604,0.499339,1.347918
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133,0.403695,1.976760
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629,0.332941,1.271952

2. Calculate the distance between Bern and all the cities in a new column `distance_to_bern`. You can do this by using the Haversine formula:

$$ d = r \cdot 2 \cdot \arcsin \left( \sqrt{\sin^2 \left( \frac{lat2 - lat1}{2}\right) + \cos(lat1) \cdot \cos(lat2) \cdot \sin^2 \left( \frac{lng2 - lng1}{2}\right)} \right), $$

where $lat1$ and $lat2$ are the latitudes in radians, and $lng1$ and $lng2$ the longitudes in radians, and the $r$ the radius of the Earth. 

Hints:
- For Bern, use lat=46.94798°, lng=7.44743° and $r=6371 km$. The calculated distances will be in kilometers.
- Do not forget to convert the coordinates of Bern to radians.
- There are many suitable Ufuncs to use, e.g., `np.arcsin`.

In [30]:
# TODO
r = 6371
lat_bern = np.radians(46.94798)
lng_bern = np.radians(7.44743)

lat2 = cities_df['lat_rad']
lng2 = cities_df['lng_rad']

# Haversine formula
dlat = cities_df['lat_rad'] - lat_bern
dlng = cities_df['lng_rad'] - lng_bern
a = np.sin(dlat / 2) ** 2 + np.cos(lat_bern) * np.cos(cities_df['lat_rad']) * np.sin(dlng / 2) ** 2
cities_df['distance_to_bern'] = r * 2 * np.arcsin(np.sqrt(a))

cities_df[['city', 'distance_to_bern']].head()

        city  distance_to_bern
0      Tokyo       9669.087498
1    Jakarta      11220.366236
2      Delhi       6243.601285
3  Guangzhou       9266.971110
4     Mumbai       6619.436079

3. Does your code use broadcasting? If yes, indicate where.

**Your answer**: TODO

4. Sort the dataframe by your calculated distances, such that the lowest distance to Bern is the first row. Print the first 7 rows of the sorted dataframe.

In [31]:
# TODO
cities_df.sort_values(by='distance_to_bern').head(7)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,lat_rad,lng_rad,distance_to_bern
4641,Bern,Bern,46.9480,7.4474,Switzerland,CH,CHE,Bern,primary,134506.0,1756374318,0.819397,0.129982,0.003183
27138,Ostermundigen,Ostermundigen,46.9553,7.4833,Switzerland,CH,CHE,Bern,NaN,17751.0,1756779389,0.819525,0.130608,2.841717
34076,Muri,Muri,46.9319,7.4872,Switzerland,CH,CHE,Bern,NaN,13054.0,1756349869,0.819116,0.130676,3.509044
13163,Köniz,Koniz,46.9250,7.4153,Switzerland,CH,CHE,Bern,NaN,41784.0,1756022220,0.818996,0.129421,3.532753
37369,Belp,Belp,46.8914,7.4972,Switzerland,CH,CHE,Bern,NaN,11510.0,1756855405,0.818409,0.130851,7.339616
43767,Wohleiberg,Wohleiberg,46.9719,7.3569,Switzerland,CH,CHE,Bern,NaN,9281.0,1756011124,0.819814,0.128402,7.367343
37820,Worb,Worb,46.9306,7.5644,Switzerland,CH,CHE,Bern,NaN,11311.0,1756060343,0.819093,0.132024,9.088315